name: Transpilacion de EMCN01 a JavasScript

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**'
      - 'tsconfig.json'
      - 'package.json'

# AGREGAR PERMISOS
permissions:
  contents: write
  actions: read

jobs:
  transpile-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # Usar token por defecto

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: |
          # Usar npm install en lugar de npm ci para evitar problemas de sincronización
          npm install
          
          # Verificar que todas las dependencias estén instaladas
          npm ls --depth=0

      - name: Build TypeScript
        run: npm run build

      - name: Install production dependencies only
        run: |
          # Crear package.json solo con dependencias de producción
          echo '{
            "name": "transpiled-production",
            "version": "1.0.0",
            "main": "index.js",
            "dependencies": {
              "pg": "^8.11.0",
              "mongodb": "^6.0.0"
            }
          }' > package-prod.json
          
          # Instalar solo dependencias de producción en directorio separado
          mkdir -p prod-modules
          cd prod-modules
          cp ../package-prod.json ./package.json
          npm install --production
          cd ..

      - name: Checkout transpiled branch
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # Cambiar a rama transpilada (crear si no existe)
          git checkout -B transpilado
          
          # Limpiar rama completamente
          git rm -rf . || true
          
          # Copiar archivos JavaScript transpilados
          cp -r dist/* .
          
          # Copiar node_modules de producción
          cp -r prod-modules/node_modules ./
          
          # Crear package.json mínimo para la rama transpilada
          echo '{
            "name": "transpiled-production",
            "version": "1.0.0",
            "main": "index.js",
            "dependencies": {
              "pg": "^8.11.0",
              "mongodb": "^6.0.0"
            }
          }' > package.json
          
          # Commit y push con token
          git add .
          git commit -m "Auto-transpile from master $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git transpilado --force